# Generated by Django 3.0.5 on 2025-12-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_customerfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerFeedback',
        ),
    ]
